### Ejercicios scraping

In [ ]:
# Importa as librarías necesarias para as tarefas de scraping

In [7]:

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
#Scrapea a pagina de sensacine para obter o nome da pelicula e data de estreno dos estreos mais esperados.
#https://www.sensacine.com/

In [8]:
url = 'https://www.sensacine.com/'
paxina = requests.get(url)
soup = BeautifulSoup(paxina.content, 'html.parser')
div=soup.find_all('div', {'class':'title-wrapper'})

In [9]:

for nova in div:
    print(nova.find('a').text,nova.find('div',{'class': 'list-entity-item-director'}))
novas = []
for nova in div:
    #print(nova.find('h2').text)
    novas.append([nova.find('a').text,nova.find('div',{'class': 'list-entity-item-director'}).text])
print(novas)

 Morbius  <div class="list-entity-item-director">1 de abril de 2022</div>
 El hombre del Norte <div class="list-entity-item-director">22 de abril de 2022</div>
 A través de mi ventana <div class="list-entity-item-director">4 de febrero de 2022</div>
 Doctor Strange en el Multiverso de la Locura <div class="list-entity-item-director">6 de mayo de 2022</div>
 The Batman <div class="list-entity-item-director">4 de marzo de 2022</div>
 Sonic, la película 2 <div class="list-entity-item-director">8 de abril de 2022</div>
 Uncharted <div class="list-entity-item-director">11 de febrero de 2022</div>
 Red <div class="list-entity-item-director">11 de marzo de 2022</div>
 Cásate conmigo <div class="list-entity-item-director">25 de febrero de 2022</div>
 La abuela <div class="list-entity-item-director">28 de enero de 2022</div>
[[' Morbius ', '1 de abril de 2022'], [' El hombre del Norte', '22 de abril de 2022'], [' A través de mi ventana', '4 de febrero de 2022'], [' Doctor Strange en el Multiverso de la Locura', '6 de mayo de 2022'], [' The Batman', '4 de marzo de 2022'], [' Sonic, la película 2', '8 de abril de 2022'], [' Uncharted', '11 de febrero de 2022'], [' Red', '11 de marzo de 2022'], [' Cásate conmigo', '25 de febrero de 2022'], [' La abuela', '28 de enero de 2022']]

In [ ]:
#Crear un dataFrame cos datos obtidos

In [10]:
df_titulos = pd.DataFrame(novas,columns = ['título','DataEstreno'])
df_titulos = df_titulos.set_index('DataEstreno')


df_titulos

                                                              título
DataEstreno
1 de abril de 2022                                          Morbius
22 de abril de 2022                              El hombre del Norte
4 de febrero de 2022                          A través de mi ventana
6 de mayo de 2022       Doctor Strange en el Multiverso de la Locura
4 de marzo de 2022                                        The Batman
8 de abril de 2022                              Sonic, la película 2
11 de febrero de 2022                                      Uncharted
11 de marzo de 2022                                              Red
25 de febrero de 2022                                 Cásate conmigo
28 de enero de 2022                                        La abuela

In [ ]:
#Obten da paxina gastronomia de galicia o nome de todas as receitas de Marisco e crea con elas un DataFrame
#http://www.gastronomiadegalicia.com/v_portal/apartados/apartado.asp?te=499

In [5]:
url = 'http://www.gastronomiadegalicia.com/v_portal/apartados/apartado.asp?te=499'
paxina = requests.get(url)
soup = BeautifulSoup(paxina.content, 'html.parser')
receitas=[]
result = soup.find_all('li')
for rec in result:
   
    solo=rec.find_all('a',{'title':'Ver'})
    for s in solo:
        receitas.append(s.text.strip('(\r)(\n)'))
        
import pandas as pd
rec = pd.DataFrame(receitas,columns = ['Receita'])  
rec

                                              Receita
0               Acedías en zume de caldeirada cítr...
1                              A cocción dos mariscos
2                        Ameixas en salsa de albariño
3               Arroz Meloso de Moluscos co seu cr...
4               Berberechos, ñoquis de pataca en s...
5                                  Bombóns de Centola
6                   Choco á prancha con crema de allo
7                                  Choco na súa tinta
8                     Espetos de ostras con champiñón
9                                    Langosta guisada
10              Langosta vermella  de costa fervid...
11                            Maridaxe de Arzúa(copia
12                                    Nécoras recheas
13                                Ostras escabechadas
14                                    Ostras fritidas
15                                   Ourizos da Veira
16                     Percebes ao aroma de San Xurxo
17              Percebes ao estilo tradicional, tr...
18              Polbo á arousana con emulsión de a...
19                                      Polbo á feira
20              Polbo á prancha con cachelo e chim...
21              Polbo á prancha con crema de colif...
22              Polbo á prancha con crema de tubér...
23              Polbo con pemento sobre tosta de c...
24              Raviolis de centola con sopa de peixe
25              Revolto de ourizos, alcachofas e t...
26                                Salpicón de Centola
27                       Salteado de ostras con polbo
28                           Sopa de Peixe e Mariscos
29              Tronco de langosta vermella de cos...
30                  Vieira poêle con aceite de trufas
31                                Vieiras ao Albariño
32              Vieiras ao Albariño no restaurante...
33                                   Vieiras á galega
34              Vieiras curadas en auga de mar con...
35              Volováns recheos de guacamole e me...

In [ ]:
#Scrapea a seguinte web:
#Mostra os atributos da tabla

In [11]:
url = 'https://www.miteco.gob.es/es/biodiversidad/temas/conservacion-de-especies/especies-proteccion-especial/ce-proteccion-listado-situacion.aspx'
paxina = requests.get(url)
soup = BeautifulSoup(paxina.content, 'html.parser')
soup
    
atributos=soup.table.attrs
atributos

{'id': 'xsltExecuted',
 'class': ['data-table'],
 'cellspacing': '0',
 'cellpadding': '0',
 'summary': 'Listado de Especies en Régimen de Protección Especial'}

In [ ]:
#Mostra o valor de summary

In [100]:

atributos.get('summary')

'Listado de Especies en Régimen de Protección Especial'

In [ ]:
#Da tabla que hay na web crea unha lista cos invertebrados e os seus valores

In [95]:

url = 'https://www.miteco.gob.es/es/biodiversidad/temas/conservacion-de-especies/especies-proteccion-especial/ce-proteccion-listado-situacion.aspx'
paxina = requests.get(url)
soup = BeautifulSoup(paxina.content, 'html.parser')
soup
    
soup.table.attrs
taboa = soup.find(class_='data-table')
taboa

lista = []

for fila in taboa.find_all('tr'):
    temp_lista = []
    for elemento in fila.find_all(['td','th']):
        temp_lista.append(elemento.text.strip())
    lista.append(temp_lista)
lista
l= lista[3]
print(l)

['INVERTEBRADOS', '67', '15', '20', '102']

In [108]:
#Scrapea a seguinte paxina e reproduce  a tabla de listas de patrons que se atopa o final da mesma 
#url = 'https://www.miteco.gob.es/es/biodiversidad/servicios/banco-datos-naturaleza/informacion-disponible/BDN_listas_patron.aspx'

In [12]:

url = 'https://www.miteco.gob.es/es/biodiversidad/servicios/banco-datos-naturaleza/informacion-disponible/BDN_listas_patron.aspx'
paxina = requests.get(url)
soup = BeautifulSoup(paxina.content, 'html.parser')

In [13]:
soup.table.attrs
taboa = soup.find(class_='data-table')
taboa

lista = []

for fila in taboa.find_all('tr'):
    temp_lista = []
    for elemento in fila.find_all(['td','th']):
        temp_lista.append(elemento.text.strip())
    lista.append(temp_lista)

In [36]:
import pandas as pd
rec = pd.DataFrame(lista,columns = ['Temática','Sociedad Cientifica'])  

rec

,Temática,Sociedad Cientifica
0,,None
1,Temática,Sociedad científica
2,Anfibios y Reptiles,Asociación Herpetológica Española (AHE)
3,Aves,Sociedad Española de Ornitología (SEO-BirdLife)
4,Briófitos,Sociedad Española de Briología (SEB)
5,Especies Marinas,"Grupo expertos coordinados por MITECO (CSIC, I..."
6,Flora vascular,Real Jardín Botánico (CSIC) - Sociedad Español...
7,Hongos,Real Jardín Botánico (CSIC)
8,Invertebrados,"Varios (MNCN-CSIC, Zerynthia, Universidades, A..."
9,Mamíferos (excepto murciélagos),Sociedad Española para la Conservación y el Es...
10,Moluscos,Sociedad Española de Malacología (SEM)
11,Murciélagos,Asociación Española para la Conservación y el ...
12,Peces,Sociedad Ibérica de Ictiología (SIBIC)
13,Varios,Banco de Datos de la Biodiversidad de Canarias...

In [37]:
rec=rec.drop(rec.index[[0,1]]) #asi borramos os indices
rec

,Temática,Sociedad Cientifica
2,Anfibios y Reptiles,Asociación Herpetológica Española (AHE)
3,Aves,Sociedad Española de Ornitología (SEO-BirdLife)
4,Briófitos,Sociedad Española de Briología (SEB)
5,Especies Marinas,"Grupo expertos coordinados por MITECO (CSIC, I..."
6,Flora vascular,Real Jardín Botánico (CSIC) - Sociedad Español...
7,Hongos,Real Jardín Botánico (CSIC)
8,Invertebrados,"Varios (MNCN-CSIC, Zerynthia, Universidades, A..."
9,Mamíferos (excepto murciélagos),Sociedad Española para la Conservación y el Es...
10,Moluscos,Sociedad Española de Malacología (SEM)
11,Murciélagos,Asociación Española para la Conservación y el ...
12,Peces,Sociedad Ibérica de Ictiología (SIBIC)
13,Varios,Banco de Datos de la Biodiversidad de Canarias...